// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Position struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Quantity           float64
	AveragePrice       float64
	CurrentPrice       int64
	Ppl                float64
	Ticker             string
	Securitytype       sql.NullString
	PreviousClosePrice sql.NullInt64
}
