// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: positions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPosition = `-- name: CreatePosition :one
insert into positions (id, created_at, updated_at, quantity, average_price, current_price, ppl, ticker)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, created_at, updated_at, quantity, average_price, current_price, ppl, ticker
`

type CreatePositionParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Quantity     float64
	AveragePrice float64
	CurrentPrice float64
	Ppl          float64
	Ticker       string
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Quantity,
		arg.AveragePrice,
		arg.CurrentPrice,
		arg.Ppl,
		arg.Ticker,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.AveragePrice,
		&i.CurrentPrice,
		&i.Ppl,
		&i.Ticker,
	)
	return i, err
}

const deletePoistion = `-- name: DeletePoistion :one
delete from positions where id = $1
returning id, created_at, updated_at, quantity, average_price, current_price, ppl, ticker
`

func (q *Queries) DeletePoistion(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRowContext(ctx, deletePoistion, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.AveragePrice,
		&i.CurrentPrice,
		&i.Ppl,
		&i.Ticker,
	)
	return i, err
}

const getLastPositionsTodayByTickerExcludingCurrent = `-- name: GetLastPositionsTodayByTickerExcludingCurrent :many
select id, created_at, updated_at, quantity, average_price, current_price, ppl, ticker from positions where ticker = $1 and id != $2 and date(created_at) = CURRENT_DATE order by created_at desc
`

type GetLastPositionsTodayByTickerExcludingCurrentParams struct {
	Ticker string
	ID     uuid.UUID
}

func (q *Queries) GetLastPositionsTodayByTickerExcludingCurrent(ctx context.Context, arg GetLastPositionsTodayByTickerExcludingCurrentParams) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getLastPositionsTodayByTickerExcludingCurrent, arg.Ticker, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
			&i.AveragePrice,
			&i.CurrentPrice,
			&i.Ppl,
			&i.Ticker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayPositions = `-- name: GetTodayPositions :many
select id, created_at, updated_at, quantity, average_price, current_price, ppl, ticker from positions where date(created_at) = CURRENT_DATE order by created_at desc
`

func (q *Queries) GetTodayPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getTodayPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
			&i.AveragePrice,
			&i.CurrentPrice,
			&i.Ppl,
			&i.Ticker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
